<?php

namespace Database\Seeders;

use App\Models\FormQuestion;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FormQuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //for SNA
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'1',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'2',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'3',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'4',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'5',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'6',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'7',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'8',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'9',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'10',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'11',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'12',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'13',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'14',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'15',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'16',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'17',
            'q_type'=>'1'
        ]);

        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'18',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'19',
            'q_type'=>'1'
        ]);





        // for WIR
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'1',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'2',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'3',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'4',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'5',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'6',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'7',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'8',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'9',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'10',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'11',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'12',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'13',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'14',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'15',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'16',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'17',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'18',
            'q_type'=>'1'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'19',
            'q_type'=>'1'
        ]);

        // for response SNA
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'20',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'21',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'22',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'23',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'24',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'25',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'26',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'27',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'28',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'29',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'1',
            'question_id'=>'30',
            'q_type'=>'2'
        ]);


        // for response WIR
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'20',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'21',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'22',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'23',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'24',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'25',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'26',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'27',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'28',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'29',
            'q_type'=>'2'
        ]);
        FormQuestion::create([
            'form_id'=>'2',
            'question_id'=>'30',
            'q_type'=>'2'
        ]);
        









    }
}
